@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

POST {{host}}/api/auth/join
content-type: {{contentType}}

{
  "email": "asdfssg@naver.com",
  "pwd": "asksA1@aa!"
}

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "ssssasdfsg@naver.com",
  "pwd": "asksA1@aa!"
}

###
@authToken = {{login.response.body.token}}

###
