@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@server = http://118.67.129.120:3000
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###
@authToken = {{login.response.body.token}}

###

GET {{host}}/api/issue/list/5fcca3cdef5f6a1a1a774576
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

GET {{host}}/api/comment/5fccb3e7e1689a32b4ffaf45
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

post {{host}}/api/comment
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "issueId": "5fccb3e7e1689a32b4ffaf45",
  "comment": "아 내일 월요일.."
}

###
@deleteCommentId = 5fc60e25da7ce91b1807b167
delete {{host}}/api/comment/{{deleteCommentId}}
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###
@updateCommentId = 5fccb6591579f709506c1ccc
patch {{host}}/api/comment/{{updateCommentId}}
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "comment": "저녁을 맛나게 먹을겁니다."
}