@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

POST {{host}}/api/auth/join
content-type: {{contentType}}

{
  "email": "asdfsg@naver.com",
  "pwd": "asksA1@aa!"
}

###

POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "asdfsg@naver.com",
  "pwd": "asksA1@aa!"
}