@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "asdfsg@naver.com",
  "pwd": "asksA1@aa!"
}

###
@authToken = {{login.response.body.token}}

###

GET {{host}}/api/issue
?page=1
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 페이지가 없으면 에러

GET {{host}}/api/issue

### 페이지가 string이여도 에러

GET {{host}}/api/issue
?page=abc

