@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@server = http://118.67.129.120:3000
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###
@authToken = {{login.response.body.token}}
@issueId = 5fccc7d62b56dd3094f0cfce

###

GET {{host}}/api/issue/{{issueId}}
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

@projectId = 5fcca3cdef5f6a1a1a774576

###
GET {{host}}/api/issue/list/{{projectId}}
?page=1
?limit=10
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

### 이슈 resolve하기

PATCH {{host}}/api/issue
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "issueList": ["5fc5d859104030b16fdccd01"]
}