@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@server = http://118.67.129.120:3000
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###
@authToken = {{login.response.body.token}}

###

@findUser = kang
GET {{host}}/api/user/{{findUser}}
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

GET {{host}}/api/user
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

PATCH {{host}}/api/user
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "nickname": "자연인"
}