@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@server = http://192.168.0.18:3000
@host = {{server}}
@contentType = application/json

###
GET {{host}}/status

### 회원가입

POST {{host}}/api/auth/join
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###
@authToken = {{login.response.body.token}}

###

GET https://api.github.com/user
Authorization: Bearer ac3d466c22f82889b17f22b8126bbf11b06bda74