@hostname = localhost
@port = 3000
@develop = http://{{hostname}}:{{port}}
@server = http://192.168.0.18:3000
@host = {{develop}}
@contentType = application/json

###
GET {{host}}/status

###

# @name login
POST {{host}}/api/auth/login
content-type: {{contentType}}

{
  "email": "testId1@naver.com",
  "pwd": "aaAA1234@"
}

###
@authToken = {{login.response.body.token}}

### 프로젝트 작성

### 필수 정보

POST {{host}}/api/project
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "platform": "Node",
  "projectName": "첫번째 예시 폐이지"
}

### email 추가

POST {{host}}/api/project
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "platform": "Express",
  "projectName": "두번째 이메일 포함",
  "emails": ["soos0228@navercom", "soos3121@gmail.com"]
}

### 프로젝트 로드

GET {{host}}/api/project
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

###

GET {{host}}/api/project/5fcf7e139a69850fb6505b4b
content-type: {{contentType}}
Authorization: Bearer {{authToken}}

